FORTUNES_LIST = [
  "Fate can be defined as small bits of enlightenment.", 
  "Somebody has gotta scare these hoes.",
  "We’re all rats in the cage.", 
  "Benchling is the largest independent software company for scientists.", 
  "If you are safe saying retard, do not try to say faggot as well.", 
  "It must be so nice to love you.",
  "My god does play dice.", 
  "Hard work is a prison only if it does not have meaning.", 
  "The best liar lies to themselves first.",
  "I see nothing except your fat ass.", 
  "At some point you deserve a beating.", 
  "You can't have good taste and be a product manager.", 
  "Every rom-com has a happy ending.", 
  "Don't care; didn't ask.", 
  "Bake with the flour you've got.", 
  "Feel guilt but maintain indifference.", 
  "You were not meant for the Cretaceous period.", 
  "20 grams of protien is just enough to get you agressive but not enough to get you violent.", 
  "The male equivalent of being treated as a sex object is being treated as a \"success object\".", 
  "Don't sacrifice your vision for anything.", 
  "If you can't imagine a universe where your dreams are real, you should imagine different universes.", 
  "There are no mistakes, only opportunities.", 
  "Your pelvis is going to get WHACKED tonight.", 
  "There is something wrong with you if you would, maybe, gulp an oyster.", 
  "How does it feel to be so wrong?", 
  "If the day comes to a close and you still want her head on your shoulder, let her wear her weird ass clothes.", 
  "Psychological warfare committed against men should never be leaked.",
  "You are the only person whose pants I would eat off of.", 
  "Have an ego-death experience later today.", 
  "If you're really that compatible, their cat shit wont smell that bad.", 
  "Values first, aptitude second, skills third.", 
  "You cant regulate people who have all the options.", 
  "You strike me as a creature who has control over every aspect of its life; quit being a pussy.", 
  "The lover inside of everyone is erratic.", 
  "There is always at least one ball in play... and sometimes two.",
  "Are you a mexi-can or a mexi-can't?.", 
  "You've gotta take some L's; this may be one of them.", 
  "The final product is a history of the piece's becoming.",
  "A big heart does not come with silence.",
  "Do not focus on results; ask yourself to dare greatly.",
  "Get your head out of your ass.", 
  "You can't outcompete someone who is having fun.",
  "We have met the enemy and he is us.", 
  "You do not choose who you are, rather, you recognize yourself its choosing of you.", 
  "The universe will flicker and dance while it reveals its plans for you.",
  "Don't drink and drive, you'll spill it.", 
  "Don't believe in things you have to believe in", 
  "A god ignored is a demon born"]